const type = {
  CHANGE_EVENT: 'CHANGE',
  INCRMENT: 'INCRMENT',
  CREATE: 'CREATE',
  DELETE: 'DELETE',
  ADDCOUNT: 'ADDCOUNT',
  MINCOUNT: 'MINCOUNT',
  CHANGESTATE: 'CHANGESTATE'
}

export default type;